# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Youngjoon Lee
title: AI Research Scientist
email: yjlee22@kaist.ac.kr
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: yjlee22
linkedin_username: yjlee22
orcid_username: 0000-0003-4926-7702

# About Section
# about_title: About Me (Use this to override about section title)
about_content: > # this means to ignore newlines until the next config item.
  Hi, I'm <b>Youngjoon Lee</b>, a passionate self-taught AI research scientist from Republic of Korea.

content:  
  - title: Education
    layout: list
    content:
      - layout: top
        title: Korea Advanced Institute of Science and Technology
        sub_title: M.S., Electric and Electronic Engineering
        caption: Sep. 2019 - Aug. 2021
        # quote: >
        #   Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Advisor: Prof. Joonhyuk Kang

          Thesis: Statistical Heterogeneity-aware Federated Approach and Application
      
      - layout: top
        title: Ulsan National Institute of Science and Technology
        sub_title: B.S., Electric and Electronic Engineering, <i>magna cum laude</i>
        caption: Mar. 2015 - Aug. 2019
  
  - title: Employment
    layout: list
    content:
      - layout: top
        title: Korea Institute of Industrial Technology
        sub_title: Technical Research Personnel
        caption: Sep. 2021 - present
        description: | # this will include new lines to allow paragraphs
          Future-oriented manufacturing-system core technology and processing technology development

  - title: Research Interest
    layout: text
    content: | # this will include new lines to allow paragraphs
      Distributed Machine Learning
      - Federated Learning
      - Split Learning
    
      Learning Theory
      - Supervised Learning
      - Meta Learning
      - Self-Supervised Learning

  - title: Project Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Development of Communications and Computing Technology for Super-intelligent Services
        caption: Sep. 2020 - Aug. 2021
        quote: >
          Sponsor: Institute of Information & Communications Technology Planning & Evaluation
        description: | # this will include new lines to allow paragraphs
          Subjects: This project is aimed to develop federated learning system based on edge computing.
            
            - Developed transmission strategy for uplink communication for federated learning system
         
            - Developed machine learning model compression and reconstruction strategy using neural networks
           
            - Developed federated learning system, which assures robustness of device and data heterogeneity

      - layout: top
        title: Design of Frequency Invariant Beam Generator
        caption: Nov. 2020 - Aug. 2021
        quote: >
          Sponsor: ADD (Agency for Defense Development), Republic of Korea
        description: | # this will include new lines to allow paragraphs
          Subjects: This project is aimed to develop frequency invariant beam generator, which eliminates noise through neural network. (Project leader)
                   
            - Developed frequency invariant beam generation model using transformer based autoencoder
                  
            - Developed CNN-based feature extractor model through contrastive learning for datasets without labels
  
  - title: Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: SCI Journal
        description: | # this will include new lines to allow paragraphs
          <u><b>Youngjoon Lee</b></u>, Sangwoo Park and Joonhyuk Kang, “RSFL: Robust and Safe Federated Learning in Heterogeneous Environments”, <i>IEEE Internet of Things Journal</i>, in preparation
          
          <u><b>Youngjoon Lee</b></u>, Sangwoo Park, Jinhyun Ahn and Joonhyuk Kang, “Accerlerated Federated Learning via Greedy Aggregation”, <i>IEEE Signal Processing Letters</i>, in preparation
      - layout: top
        title: Conference
        description: | # this will include new lines to allow paragraphs
          <u><b>Youngjoon Lee</b></u>, Taesoo Kim, Jinhyun Ahn and Joonhyuk Kang, “FedMusic: Automatic Music Transcription System Powered by Federated Learning”, <i>IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)</i>, June, 2022, under review

          <u><b>Youngjoon Lee</b></u> and Joonhyuk Kang, “FedLN: Federated Learning with Local Normalization”, <i>Joint Conference on Communications and Information (JCCI)</i>, April, 2021
      - layout: top
        title: Patent
        description: | # this will include new lines to allow paragraphs
          “Nerual Network Training Method and Appratus Using Federated Learning”, <u><b>Youngjoon Lee</b></u>, Joonhyuk Kang, Registration No. 10-2021-0148110, 2021

          “Federated Learning Method and System”, <u><b>Youngjoon Lee</b></u>, Joonhyuk Kang, Registration No. 10-2021-0016897, 2021


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
