# Site
repository: yjlee22/yjlee22.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Youngjoon Lee
title: AI Research Scientist
email: yjlee22@kaist.ac.kr
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
#website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: yjlee22
linkedin_username: yjlee22
orcid_username: 0000-0003-4926-7702

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: ./images/yjlee_v2.jpg
about_content: > # this means to ignore newlines until the next config item.
  Hi, I'm <b>Youngjoon Lee</b>, a passionate self-taught AI research scientist from Republic of Korea.
  I received B.S. degree  in electric and electronic engineering from Ulsan National Institute of Science and Technology (UNIST),  Ulsan, Republic of Korea, in 2019 and M.S. degree in electric and electronic engineering from Korea Advanced Institute of Science and Technology (KAIST), Daejon, Republic of Korea, in 2021.
  I'm currently a technical research personnel for alternative military service at Korea Institute of Industrial Technology (KITECH), Republic of Korea.
  The ongoing research goal is to develop future-oriented core technology and processing technologies for industrial systems.
  My  recent research interests lie in the field of distributed machine learning and learning theory, with a specific focus on federated learning.
  
content:  
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: KAIST
        sub_title: M.S., Electric and Electronic Engineering
        caption: Sep. 2019 - Aug. 2021
        quote: >
          KAIST is the first and top science and technology university in Republic of Korea.
        description: | # this will include new lines to allow paragraphs
          During my time at KAIST, I studied the problem of improving the performance of federated learning under the guidance of Prof. Joonhyuk Kang.
          I solved the problems of federated learning, statistical heterogeneity and system heterogeneity, through neural networks and mathematical modeling.
          To reach my goal, I studied further into distributed machine learning and learning theory.
      
      - layout: top-left
        title: UNIST
        sub_title: B.S., Electric and Electronic Engineering, <i>magna cum laude</i>
        caption: Mar. 2015 - Aug. 2019
        quote: >
          UNIST is a post-secondary institution which is dedicated to research in science and technology in Republic of Korea.
        description: | # this will include new lines to allow paragraphs
          During my time at UNIST, I studied on bio-signal processing based on machine learning under the guidance of Prof. Jin-Ho Chung. 
          I developed a bio-data analysis engine, which detects a unique pattern in the signal of the human body by integrating electrical engineering and bio-medical engineering. 
          To reach my goal, I studied further into bio system modeling and analysis technique based on multi-layer neural network.

  - title: Project Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Development of Communications and Computing Technology for Super-intelligent Services
        caption: Oct. 2020 - Aug. 2021
        quote: >
          Sponsor: IITP (Institute of Information & Communications Technology Planning & Evaluation), Republic of Korea
        description: | # this will include new lines to allow paragraphs
          Subjects: This project is aimed to develop federated learning system based on edge computing.
            
            - Developed transmission strategy for uplink communication for federated learning system
         
            - Developed machine learning model compression and reconstruction strategy using neural networks
           
            - Developed federated learning system, which assures robustness of device and data heterogeneity

      - layout: top
        title: Design of Frequency Invariant Beam Generator
        caption: Nov. 2020 - Aug. 2021
        quote: >
          Sponsor: ADD (Agency for Defense Development), Republic of Korea
        description: | # this will include new lines to allow paragraphs
          Subjects: This project is aimed to develop frequency invariant beam generator, which eliminates noise through neural network. (Project leader)
                   
            - Developed frequency invariant beam generation model using attention based auto-encoder
                  
            - Developed CNN-based feature extractor model through contrastive learning for datasets without labels
  
  - title: Publication
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        caption: <b>Journal</b>  
        description: | # this will include new lines to allow paragraphs                    
          - <u><b>Youngjoon Lee</b></u>, Sangwoo Park and Joonhyuk Kang, “Fast-convergent Federated Learning via Cyclic Aggregation”, <i>IEEE Communications Letters</i>, <i>in preparation</i>

          - <u><b>Youngjoon Lee</b></u>, Sangwoo Park, Jin-hyun Ahn and Joonhyuk Kang, “Accelerated Federated Learning via Greedy Aggregation”, <i>IEEE Communications Letters</i>, <i>under review</i>
      
      - layout: top-left
        caption: <b>Conference</b>
        description: | # this will include new lines to allow paragraphs
          - <u><b>Youngjoon Lee</b></u>, Taesoo Kim, Jin-hyun Ahn and Joonhyuk Kang, “FedMusic: Automatic Music Transcription System Powered by Federated Learning”, <i>IEEE ICTC 2022</i>, under review

          - <u><b>Youngjoon Lee</b></u>, Sangwoo Park and Joonhyuk Kang, “Byzantine-Resilient Federated Learning via Reverse Aggregation”, <i>Interspeech 2022</i>, under review

          - <u><b>Youngjoon Lee</b></u> and Joonhyuk Kang, “FedLN: Federated Learning with Local Normalization”, <i>Joint Conference on Communications and Information (JCCI)</i>, April, 2021
      - layout: top-left
        caption: <b>Patent</b>
        description: | # this will include new lines to allow paragraphs
          - “Method and System for Byzantine-Resilient and Personalized Distributed Learning”, <u><b>Youngjoon Lee</b></u>, Sangwoo Park, Joonhyuk Kang, Registration No. 10-2022-0065524, 2022

          - “Nerual Network Training Method and Appratus Using Federated Learning”, <u><b>Youngjoon Lee</b></u>, Sangwoo Park, Joonhyuk Kang, Registration No. 10-2021-0148110, 2021

          - “Federated Learning Method and System”, <u><b>Youngjoon Lee</b></u>, Sangwoo Park, Joonhyuk Kang, Registration No. 10-2390553-0000, 2022


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
